
var data={
     _mockChannels :[{
        "mature": false,
        "partner": false,
        "status": "Невероятная череда побед",
        "broadcaster_language": "ru",
        "display_name": "Eligorko",
        "game": "PLAYERUNKNOWN'S BATTLEGROUNDS",
        "language": "en",
        "_id": 24058100,
        "name": "eligorko",
        "created_at": "2011-08-13T20:17:50Z",
        "updated_at": "2017-09-05T12:00:43Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/6953d44d9c8254ed-profile_image-300x300.png",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eligorko-channel_offline_image-50d8ecc3d9df56f5-1920x1080.jpeg",
        "background": null,
        "profile_banner": null,
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/eligorko",
        "views": 5399711,
        "followers": 96243,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/eligorko",
            "follows": "https://api.twitch.tv/kraken/channels/eligorko/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/eligorko/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/eligorko/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/eligorko",
            "features": "https://api.twitch.tv/kraken/channels/eligorko/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/eligorko/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/eligorko/editors",
            "teams": "https://api.twitch.tv/kraken/channels/eligorko/teams",
            "videos": "https://api.twitch.tv/kraken/channels/eligorko/videos"
        }
    },
    {
        "mature": false,
        "partner": false,
        "status": "short stream before prac, warming up and answering Qs | @LiquidEliGE",
        "broadcaster_language": "en",
        "display_name": "EliGE",
        "game": "Counter-Strike: Global Offensive",
        "language": "en",
        "_id": 27785321,
        "name": "elige",
        "created_at": "2012-01-27T21:31:10Z",
        "updated_at": "2017-09-05T10:30:28Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/elige-profile_image-19a790071cfc5fc6-300x300.jpeg",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elige-channel_offline_image-3c845cfa4f17791f-1920x1080.png",
        "background": null,
        "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elige-profile_banner-135f12b2f693473e-480.png",
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/elige",
        "views": 475261,
        "followers": 49368,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/elige",
            "follows": "https://api.twitch.tv/kraken/channels/elige/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/elige/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/elige/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/elige",
            "features": "https://api.twitch.tv/kraken/channels/elige/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/elige/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/elige/editors",
            "teams": "https://api.twitch.tv/kraken/channels/elige/teams",
            "videos": "https://api.twitch.tv/kraken/channels/elige/videos"
        }
    },
    {
        "mature": false,
        "partner": false,
        "status": "Çılgın şeyler (っ◕‿◕)っ",
        "broadcaster_language": "tr",
        "display_name": "Elissacrn",
        "game": "IRL",
        "language": "tr",
        "_id": 145450884,
        "name": "elissacrn",
        "created_at": "2017-01-21T15:10:56Z",
        "updated_at": "2017-09-05T12:00:45Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/18830e630d995673-profile_image-300x300.jpeg",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/f6fb5c148b1be904-channel_offline_image-1920x1080.png",
        "background": null,
        "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/c328b4de9d2f0184-profile_banner-480.jpeg",
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/elissacrn",
        "views": 437403,
        "followers": 42146,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/elissacrn",
            "follows": "https://api.twitch.tv/kraken/channels/elissacrn/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/elissacrn/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/elissacrn/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/elissacrn",
            "features": "https://api.twitch.tv/kraken/channels/elissacrn/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/elissacrn/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/elissacrn/editors",
            "teams": "https://api.twitch.tv/kraken/channels/elissacrn/teams",
            "videos": "https://api.twitch.tv/kraken/channels/elissacrn/videos"
        }
    },
    {
        "mature": false,
        "partner": false,
        "status": "Ganando un Overwatch w/ RobertoCein // @eliazOne en Twitter",
        "broadcaster_language": "es",
        "display_name": "ELIAZONE",
        "game": "Overwatch",
        "language": "es",
        "_id": 99186412,
        "name": "eliazone",
        "created_at": "2015-08-14T04:56:26Z",
        "updated_at": "2017-09-05T11:30:41Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/5c66345f1629dae7-profile_image-300x300.png",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eliazone-channel_offline_image-6f8fc202caa899de-1920x1080.png",
        "background": null,
        "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eliazone-profile_banner-80e24c9f941256e2-480.jpeg",
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/eliazone",
        "views": 333100,
        "followers": 34459,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/eliazone",
            "follows": "https://api.twitch.tv/kraken/channels/eliazone/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/eliazone/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/eliazone/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/eliazone",
            "features": "https://api.twitch.tv/kraken/channels/eliazone/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/eliazone/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/eliazone/editors",
            "teams": "https://api.twitch.tv/kraken/channels/eliazone/teams",
            "videos": "https://api.twitch.tv/kraken/channels/eliazone/videos"
        }
    },
    {
        "mature": false,
        "partner": false,
        "status": "( ͡ᵔ ͜ʖ ͡ᵔ ) HeyGuys  - !giveaway 247/300 Sub Points - Road to 20k followers! <3  !montage !naire",
        "broadcaster_language": "en",
        "display_name": "Eli_X",
        "game": "Halo 5: Guardians",
        "language": "en",
        "_id": 10692319,
        "name": "eli_x",
        "created_at": "2010-02-21T06:22:11Z",
        "updated_at": "2017-09-05T09:33:52Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/4433156cc53d4bd9-profile_image-300x300.png",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eli_x-channel_offline_image-31229008e59e6e95-1920x1080.png",
        "background": null,
        "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eli_x-profile_banner-0c68e6ff7a77fad4-480.jpeg",
        "profile_banner_background_color": "#0f0e0e",
        "url": "https://www.twitch.tv/eli_x",
        "views": 168349,
        "followers": 19723,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/eli_x",
            "follows": "https://api.twitch.tv/kraken/channels/eli_x/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/eli_x/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/eli_x/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/eli_x",
            "features": "https://api.twitch.tv/kraken/channels/eli_x/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/eli_x/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/eli_x/editors",
            "teams": "https://api.twitch.tv/kraken/channels/eli_x/teams",
            "videos": "https://api.twitch.tv/kraken/channels/eli_x/videos"
        }
    },
    {
        "mature": true,
        "partner": false,
        "status": "The Empire - Turn 122+ !campaign !next !250 !hrv",
        "broadcaster_language": "en",
        "display_name": "ElichTV",
        "game": "Total War: WARHAMMER",
        "language": "en",
        "_id": 30866055,
        "name": "elichtv",
        "created_at": "2012-05-28T01:42:05Z",
        "updated_at": "2017-09-05T12:00:32Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/1d28b2b310f5cb42-profile_image-300x300.jpeg",
        "banner": null,
        "video_banner": null,
        "background": null,
        "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elichtv-profile_banner-9c2469b85c695e2d-480.jpeg",
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/elichtv",
        "views": 673980,
        "followers": 16845,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/elichtv",
            "follows": "https://api.twitch.tv/kraken/channels/elichtv/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/elichtv/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/elichtv/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/elichtv",
            "features": "https://api.twitch.tv/kraken/channels/elichtv/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/elichtv/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/elichtv/editors",
            "teams": "https://api.twitch.tv/kraken/channels/elichtv/teams",
            "videos": "https://api.twitch.tv/kraken/channels/elichtv/videos"
        }
    },
    {
        "mature": false,
        "partner": false,
        "status": "☀Летний розыгрыш от EliteCase в честь скорого ГЛОБАЛЬНОГО обновления!☀",
        "broadcaster_language": "ru",
        "display_name": "elitecase",
        "game": "Talk Shows",
        "language": "ru",
        "_id": 113889833,
        "name": "elitecase",
        "created_at": "2016-01-25T22:31:41Z",
        "updated_at": "2017-09-05T08:00:44Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/elitecase-profile_image-56e285d850fd5b68-300x300.png",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elitecase-channel_offline_image-617a978102972da7-1920x1080.png",
        "background": null,
        "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elitecase-profile_banner-3d05b2e58a8767bf-480.jpeg",
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/elitecase",
        "views": 330348,
        "followers": 16537,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/elitecase",
            "follows": "https://api.twitch.tv/kraken/channels/elitecase/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/elitecase/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/elitecase/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/elitecase",
            "features": "https://api.twitch.tv/kraken/channels/elitecase/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/elitecase/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/elitecase/editors",
            "teams": "https://api.twitch.tv/kraken/channels/elitecase/teams",
            "videos": "https://api.twitch.tv/kraken/channels/elitecase/videos"
        }
    },
    {
        "mature": true,
        "partner": false,
        "status": "EU (OPEN SESSION) Official DoN n Viewers",
        "broadcaster_language": "en",
        "display_name": "Elite_Gaming_Network",
        "game": "Tom Clancy's Rainbow Six: Siege",
        "language": "en-gb",
        "_id": 76623654,
        "name": "elite_gaming_network",
        "created_at": "2014-12-06T01:10:11Z",
        "updated_at": "2017-09-05T09:00:06Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/elite_gaming_network-profile_image-ae92318c006198c0-300x300.png",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elite_gaming_network-channel_offline_image-38ab6b15f282f8a1-1920x1080.png",
        "background": null,
        "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elite_gaming_network-profile_banner-4eed2c0948b983b3-480.png",
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/elite_gaming_network",
        "views": 16639,
        "followers": 14535,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/elite_gaming_network",
            "follows": "https://api.twitch.tv/kraken/channels/elite_gaming_network/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/elite_gaming_network/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/elite_gaming_network/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/elite_gaming_network",
            "features": "https://api.twitch.tv/kraken/channels/elite_gaming_network/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/elite_gaming_network/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/elite_gaming_network/editors",
            "teams": "https://api.twitch.tv/kraken/channels/elite_gaming_network/teams",
            "videos": "https://api.twitch.tv/kraken/channels/elite_gaming_network/videos"
        }
    },
    {
        "mature": false,
        "partner": false,
        "status": "The Weekly Pull LIVE!",
        "broadcaster_language": "en",
        "display_name": "EligibleMonster",
        "game": "Talk Shows",
        "language": "en",
        "_id": 37198239,
        "name": "eligiblemonster",
        "created_at": "2012-10-27T01:49:28Z",
        "updated_at": "2017-09-05T08:03:40Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/eligiblemonster-profile_image-09a83a165cbd37c0-300x300.png",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eligiblemonster-channel_offline_image-63d3627c0f3f17da-1920x1080.jpeg",
        "background": null,
        "profile_banner": null,
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/eligiblemonster",
        "views": 226406,
        "followers": 14818,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/eligiblemonster",
            "follows": "https://api.twitch.tv/kraken/channels/eligiblemonster/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/eligiblemonster/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/eligiblemonster/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/eligiblemonster",
            "features": "https://api.twitch.tv/kraken/channels/eligiblemonster/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/eligiblemonster/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/eligiblemonster/editors",
            "teams": "https://api.twitch.tv/kraken/channels/eligiblemonster/teams",
            "videos": "https://api.twitch.tv/kraken/channels/eligiblemonster/videos"
        }
    },
    {
        "mature": false,
        "partner": false,
        "status": "offline",
        "broadcaster_language": "cs",
        "display_name": "ElitheCat",
        "game": "",
        "language": "cs",
        "_id": 150451400,
        "name": "elithecat",
        "created_at": "2017-03-14T21:59:33Z",
        "updated_at": "2017-09-05T11:32:08Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/elithecat-profile_image-af4ec1c6d6c5a88e-300x300.jpeg",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/e5c7c4ae66da34dd-channel_offline_image-1920x1080.png",
        "background": null,
        "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elithecat-profile_banner-db53aa077b5a7cb5-480.jpeg",
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/elithecat",
        "views": 82620,
        "followers": 17977,
        "_links": {
            "self": "https://api.twitch.tv/kraken/channels/elithecat",
            "follows": "https://api.twitch.tv/kraken/channels/elithecat/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/elithecat/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/elithecat/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/elithecat",
            "features": "https://api.twitch.tv/kraken/channels/elithecat/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/elithecat/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/elithecat/editors",
            "teams": "https://api.twitch.tv/kraken/channels/elithecat/teams",
            "videos": "https://api.twitch.tv/kraken/channels/elithecat/videos"
        }
    }
],
 _mockWatchlist:[
    24058100,
    99186412,
    30866055,
    113889833,
    10692319
],
_mockUsers:[{
    "mature": false,
    "partner": false,
    "status": "Опять победа? | 50% скидка на подписку - только в сентябре :-O",
    "broadcaster_language": "ru",
    "display_name": "Eligorko",
    "game": "PLAYERUNKNOWN'S BATTLEGROUNDS",
    "language": "en",
    "_id": 24058100,
    "name": "eligorko",
    "created_at": "2011-08-13T20:17:50Z",
    "updated_at": "2017-09-08T13:05:04Z",
    "delay": null,
    "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/6953d44d9c8254ed-profile_image-300x300.png",
    "banner": null,
    "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eligorko-channel_offline_image-50d8ecc3d9df56f5-1920x1080.jpeg",
    "background": null,
    "profile_banner": null,
    "profile_banner_background_color": "",
    "url": "https://www.twitch.tv/eligorko",
    "views": 5417702,
    "followers": 96436,
    "_links": {
    "self": "https://api.twitch.tv/kraken/channels/eligorko",
    "follows": "https://api.twitch.tv/kraken/channels/eligorko/follows",
    "commercial": "https://api.twitch.tv/kraken/channels/eligorko/commercial",
    "stream_key": "https://api.twitch.tv/kraken/channels/eligorko/stream_key",
    "chat": "https://api.twitch.tv/kraken/chat/eligorko",
    "features": "https://api.twitch.tv/kraken/channels/eligorko/features",
    "subscriptions": "https://api.twitch.tv/kraken/channels/eligorko/subscriptions",
    "editors": "https://api.twitch.tv/kraken/channels/eligorko/editors",
    "teams": "https://api.twitch.tv/kraken/channels/eligorko/teams",
    "videos": "https://api.twitch.tv/kraken/channels/eligorko/videos"
    }
    },
    {
        "mature": false,
        "partner": false,
        "status": "BADLION UHC FFA // Stacked af🔥",
        "broadcaster_language": "es",
        "display_name": "ELIAZONE",
        "game": "Minecraft",
        "language": "es",
        "_id": 99186412,
        "name": "eliazone",
        "created_at": "2015-08-14T04:56:26Z",
        "updated_at": "2017-09-08T11:00:42Z",
        "delay": null,
        "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/5c66345f1629dae7-profile_image-300x300.png",
        "banner": null,
        "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eliazone-channel_offline_image-6f8fc202caa899de-1920x1080.png",
        "background": null,
        "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eliazone-profile_banner-80e24c9f941256e2-480.jpeg",
        "profile_banner_background_color": "",
        "url": "https://www.twitch.tv/eliazone",
        "views": 334907,
        "followers": 34696,
        "_links": {
        "self": "https://api.twitch.tv/kraken/channels/eliazone",
        "follows": "https://api.twitch.tv/kraken/channels/eliazone/follows",
        "commercial": "https://api.twitch.tv/kraken/channels/eliazone/commercial",
        "stream_key": "https://api.twitch.tv/kraken/channels/eliazone/stream_key",
        "chat": "https://api.twitch.tv/kraken/chat/eliazone",
        "features": "https://api.twitch.tv/kraken/channels/eliazone/features",
        "subscriptions": "https://api.twitch.tv/kraken/channels/eliazone/subscriptions",
        "editors": "https://api.twitch.tv/kraken/channels/eliazone/editors",
        "teams": "https://api.twitch.tv/kraken/channels/eliazone/teams",
        "videos": "https://api.twitch.tv/kraken/channels/eliazone/videos"
        }
        },
        {
            "mature": true,
            "partner": false,
            "status": "Norsca - Turn 37+ !campaign !250 !hrv !cvc !300",
            "broadcaster_language": "en",
            "display_name": "ElichTV",
            "game": "Total War: WARHAMMER",
            "language": "en",
            "_id": 30866055,
            "name": "elichtv",
            "created_at": "2012-05-28T01:42:05Z",
            "updated_at": "2017-09-08T13:01:50Z",
            "delay": null,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/1d28b2b310f5cb42-profile_image-300x300.jpeg",
            "banner": null,
            "video_banner": null,
            "background": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elichtv-profile_banner-9c2469b85c695e2d-480.jpeg",
            "profile_banner_background_color": "",
            "url": "https://www.twitch.tv/elichtv",
            "views": 681125,
            "followers": 17083,
            "_links": {
            "self": "https://api.twitch.tv/kraken/channels/elichtv",
            "follows": "https://api.twitch.tv/kraken/channels/elichtv/follows",
            "commercial": "https://api.twitch.tv/kraken/channels/elichtv/commercial",
            "stream_key": "https://api.twitch.tv/kraken/channels/elichtv/stream_key",
            "chat": "https://api.twitch.tv/kraken/chat/elichtv",
            "features": "https://api.twitch.tv/kraken/channels/elichtv/features",
            "subscriptions": "https://api.twitch.tv/kraken/channels/elichtv/subscriptions",
            "editors": "https://api.twitch.tv/kraken/channels/elichtv/editors",
            "teams": "https://api.twitch.tv/kraken/channels/elichtv/teams",
            "videos": "https://api.twitch.tv/kraken/channels/elichtv/videos"
            }
            },
            {
                "mature": false,
                "partner": false,
                "status": "☀Летний розыгрыш от EliteCase в честь скорого ГЛОБАЛЬНОГО обновления!☀",
                "broadcaster_language": "ru",
                "display_name": "elitecase",
                "game": "Talk Shows",
                "language": "ru",
                "_id": 113889833,
                "name": "elitecase",
                "created_at": "2016-01-25T22:31:41Z",
                "updated_at": "2017-09-08T12:01:30Z",
                "delay": null,
                "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/elitecase-profile_image-56e285d850fd5b68-300x300.png",
                "banner": null,
                "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elitecase-channel_offline_image-617a978102972da7-1920x1080.png",
                "background": null,
                "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/elitecase-profile_banner-3d05b2e58a8767bf-480.jpeg",
                "profile_banner_background_color": "",
                "url": "https://www.twitch.tv/elitecase",
                "views": 330409,
                "followers": 16532,
                "_links": {
                "self": "https://api.twitch.tv/kraken/channels/elitecase",
                "follows": "https://api.twitch.tv/kraken/channels/elitecase/follows",
                "commercial": "https://api.twitch.tv/kraken/channels/elitecase/commercial",
                "stream_key": "https://api.twitch.tv/kraken/channels/elitecase/stream_key",
                "chat": "https://api.twitch.tv/kraken/chat/elitecase",
                "features": "https://api.twitch.tv/kraken/channels/elitecase/features",
                "subscriptions": "https://api.twitch.tv/kraken/channels/elitecase/subscriptions",
                "editors": "https://api.twitch.tv/kraken/channels/elitecase/editors",
                "teams": "https://api.twitch.tv/kraken/channels/elitecase/teams",
                "videos": "https://api.twitch.tv/kraken/channels/elitecase/videos"
                }
                },
                {
                    "mature": false,
                    "partner": false,
                    "status": "!subtember ( ͡° ͜ʖ ͡°) Power Level Grind! (261) - 247/300 Sub Points !giveaway",
                    "broadcaster_language": "en",
                    "display_name": "Eli_X",
                    "game": "Destiny 2",
                    "language": "en",
                    "_id": 10692319,
                    "name": "eli_x",
                    "created_at": "2010-02-21T06:22:11Z",
                    "updated_at": "2017-09-08T13:05:16Z",
                    "delay": null,
                    "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/4433156cc53d4bd9-profile_image-300x300.png",
                    "banner": null,
                    "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eli_x-channel_offline_image-31229008e59e6e95-1920x1080.png",
                    "background": null,
                    "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eli_x-profile_banner-0c68e6ff7a77fad4-480.jpeg",
                    "profile_banner_background_color": "#0f0e0e",
                    "url": "https://www.twitch.tv/eli_x",
                    "views": 168995,
                    "followers": 19671,
                    "_links": {
                    "self": "https://api.twitch.tv/kraken/channels/eli_x",
                    "follows": "https://api.twitch.tv/kraken/channels/eli_x/follows",
                    "commercial": "https://api.twitch.tv/kraken/channels/eli_x/commercial",
                    "stream_key": "https://api.twitch.tv/kraken/channels/eli_x/stream_key",
                    "chat": "https://api.twitch.tv/kraken/chat/eli_x",
                    "features": "https://api.twitch.tv/kraken/channels/eli_x/features",
                    "subscriptions": "https://api.twitch.tv/kraken/channels/eli_x/subscriptions",
                    "editors": "https://api.twitch.tv/kraken/channels/eli_x/editors",
                    "teams": "https://api.twitch.tv/kraken/channels/eli_x/teams",
                    "videos": "https://api.twitch.tv/kraken/channels/eli_x/videos"
                    }
                    },
]}
module.exports = data;